### PR TITLE
Gramatical changes.

### PR DESCRIPTION
**Pull request by Jesus-QC**

### CODE REVIEW

**Comment by moddedmcplayer** [comment]
🤓actually its
I am looking for SCP: Secret Laboratory plugin ideas.
or even better
I am currently looking for SCP: Secret Laboratory plugin ideas.

**Comment by Jesus-QC** [comment]
LGTM, please merge and shut

**Comment by TheUltiOne** [comment]
That's true, I overlooked that. I'd recommend committing it to the PR or I can make one and close yours in favor of mine. What do you think?

**Comment by Jesus-QC** [comment]
Sure

**Comment by TheUltiOne** [comment]
Closed in favor of https://github.com/moddedmcplayer/moddedmcplayer/pull/3

**Pull request closed without merging**
